spring.application.name=api
# Clave  para JWT y API Key
security.api.key=2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
jwt.secret=09c53c457e150766aacce02ca27ec8929797b4a3b1093d5bc6aabc0f4b4c307d
#no configurar BD automaticamente
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#loggin spring security
logging.level.org.springframework.security=DEBUG
logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.springframework.web=DEBUG


#swagger
#ordernar por
springdoc.swagger-ui.operationsSorter=method

#DATABASE
#JDBC IN JPA
spring.datasource.url=jdbc:sqlserver://improvejg.database.windows.net:1433;databaseName=improveDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=adminjg
spring.datasource.password=ljairgt156.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=none
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# LOGS DB
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#TIME TO CONECT
#setup time to connect
# Configuracion de HikariCP (pool de conexiones)
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
# 30 segundos antes de cerrar conexiones inactivas
spring.datasource.hikari.idle-timeout=30000
# 30 minutos antes de reciclar conexiones
spring.datasource.hikari.max-lifetime=1800000
# 1 minuto para mantener conexiones activas
spring.datasource.hikari.keepalive-time=60000
# 60 segundos para esperar una conexion
spring.datasource.hikari.connection-timeout=60000
# Detectar conexiones abiertas por mas de 5s
spring.datasource.hikari.leak-detection-threshold=5000
spring.jpa.properties.hibernate.default_schema=lab
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
# Configuracion del servidor Tomcat
server.tomcat.accesslog.enabled=true
# 60 segundos antes de cerrar la conexion
server.tomcat.connection-timeout=60000
# 60 segundos para mantener conexiones abiertas
server.tomcat.keep-alive-timeout=60000
# Numero maximo de hilos en Tomcat
server.tomcat.threads.max=200
# Numero minimo de hilos inactivos
server.tomcat.threads.min-spare=10




